In [1]:
pip install numpy


Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [8]:

arr = np.array([1,2,3,4,5,6,7,8,9,10])
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
arr1 = np.arange(1,11)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
arr2 = np.arange(1,10).reshape(3,3)
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
arr3 = np.random.rand(3,5,3)
arr3

array([[[0.31979906, 0.90980845, 0.76194345],
        [0.98214928, 0.52615088, 0.40123324],
        [0.6573478 , 0.11830792, 0.73652753],
        [0.15692946, 0.29844076, 0.83370474],
        [0.80602573, 0.58325327, 0.01979823]],

       [[0.24537203, 0.68051717, 0.22859107],
        [0.12308687, 0.35463743, 0.72818429],
        [0.11503162, 0.90190081, 0.20721987],
        [0.68907459, 0.98112831, 0.25683866],
        [0.71951629, 0.39664431, 0.79861201]],

       [[0.6136751 , 0.31196976, 0.46185211],
        [0.57924843, 0.56790241, 0.46847894],
        [0.61029499, 0.51594271, 0.18555904],
        [0.04972814, 0.76383656, 0.28845913],
        [0.33253631, 0.22829811, 0.55353411]]])

In [27]:
np.shape(arr1)

(10,)

In [28]:
np.size(arr2)

9

In [34]:
print(arr3.dtype)

float64


In [35]:
data = [10, 20, 30, 40, 50, 60, 70, 80, 90]
data = np.array(data)
data

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [42]:
data[:3]

array([10, 20, 30])

In [44]:
al = data[::2]
al

array([10, 30, 50, 70, 90])

In [45]:
rev = data[::-1]
rev

array([90, 80, 70, 60, 50, 40, 30, 20, 10])

In [47]:
A = np.random.randint(1,20,size = (5))
A

array([10, 15, 12, 12,  8])

In [48]:
B = np.random.randint(1,20,size = (5))
B

array([ 6,  4, 10,  8, 19])

In [49]:
A + B

array([16, 19, 22, 20, 27])

In [50]:
A*B


array([ 60,  60, 120,  96, 152])

In [51]:
A/B

array([1.66666667, 3.75      , 1.2       , 1.5       , 0.42105263])

In [52]:
A%B

array([4, 3, 2, 4, 8])

In [54]:
np.dot(A,B)

np.int64(488)

In [1]:
# Task 4: Reshaping and Transposing
# 1. 2. Create a 1D NumPy array of 12 integers ranging from 1 to 12.
# Write a Python program to:
# o Reshape the array into a 2D array of shape (4, 3).
# o Reshape the array into a 3D array of shape (2, 2, 3).
# o Transpose the reshaped 2D array and display its shape.


import numpy as np

# Step 1: Create a 1D array with integers from 1 to 12
arr = np.arange(1, 13)

# Show the original array
print("Original 1D array:", arr)

# Step 2a: Reshape the array into 2D with shape (4, 3)
arr_2d = arr.reshape(4, 3)
print("\nReshaped to 2D array (4 rows, 3 columns):\n", arr_2d)

# Step 2b: Reshape the array into 3D with shape (2, 2, 3)
arr_3d = arr.reshape(2, 2, 3)
print("\nReshaped to 3D array (2 blocks, 2 rows, 3 columns):\n", arr_3d)

# Step 2c: Transpose the 2D array
arr_2d_transposed = arr_2d.T
print("\nTransposed 2D array:\n", arr_2d_transposed)

# Show the shape of the transposed array
print("\nShape of the transposed array:", arr_2d_transposed.shape)


Original 1D array: [ 1  2  3  4  5  6  7  8  9 10 11 12]

Reshaped to 2D array (4 rows, 3 columns):
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Reshaped to 3D array (2 blocks, 2 rows, 3 columns):
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

Transposed 2D array:
 [[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]

Shape of the transposed array: (3, 4)


In [2]:
# Task 5: Boolean Masking and Filtering
# 1. 2. Create a NumPy array with 15 random integers between 10 and 50.
# Write a Python program to:
# o Find all elements greater than 25.
# o Replace all elements less than 30 with 0.
# o Count the number of elements divisible by 5.

import numpy as np

# Step 1: Create a NumPy array with 15 random integers between 10 and 50
arr = np.random.randint(10, 51, size=15)

# Show the original array
print("Original array:", arr)

# Step 2a: Find all elements greater than 25
greater_than_25 = arr[arr > 25]
print("\nElements greater than 25:", greater_than_25)

# Step 2b: Replace all elements less than 30 with 0
arr_modified = arr.copy()  # Make a copy to keep original safe
arr_modified[arr_modified < 30] = 0
print("\nArray after replacing elements less than 30 with 0:\n", arr_modified)

# Step 2c: Count the number of elements divisible by 5
divisible_by_5 = arr[arr % 5 == 0]
count_divisible_by_5 = divisible_by_5.size
print("\nNumber of elements divisible by 5:", count_divisible_by_5)


Original array: [32 43 43 17 33 25 46 34 18 21 41 30 36 39 21]

Elements greater than 25: [32 43 43 33 46 34 41 30 36 39]

Array after replacing elements less than 30 with 0:
 [32 43 43  0 33  0 46 34  0  0 41 30 36 39  0]

Number of elements divisible by 5: 2
