# Numpy - used for mathematical calculations
- faser than python(100x)
- it is a library of python but it works in C language so it works fast
- Array(homogenious data) operations k liye ek library h
- Array k upr mathematical kaam krne k liye numpy ka cuse hota h...... but data manipulation k liye pandas ka use hota h
- multithreading bhi support krta h to or bhi fast chlta h code
- accumulation of 1d vectors( 2d array)
- any = or
- all = and
- argmax = max value ka index
- argmin = min value ka index
- iteration - nditer, ndenumerate
- 


In [7]:
!pip3 install numpy

Defaulting to user installation because normal site-packages is not writeable
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.


In [8]:
import numpy as np


In [9]:
print(np.__version__)

2.2.4


In [10]:
l1 = [1,2,3,4]
l2 = [[1,2],[3,4],[5,6]]
l3 = [[[10,20],[30,40]],[[50,60],[70,80]]]

In [11]:
n1 = np.array(l1)
n2 = np.array(l2)
n3 = np.array(l3)

In [12]:
type(n1)

numpy.ndarray

In [13]:
n1.shape


(4,)

In [14]:
n2.shape

(3, 2)

In [15]:
n3.shape # iske 3 dimenssions ye bta rhe h ki ek 3d array m kitne 2d arr. hai....
        # 2d arr. m kitne 1d arr. hai....1d arr. m kitne elements h


(2, 2, 2)

In [16]:
n3.ndim # tell the no. of dimenssions

3

In [17]:
l4 = [[1,2,3],[3,4],[5,6]]
n4 = np.array(l4)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

In [ ]:
l4 = [[1,2,3],[3,4],[5,6]]
n4 = np.array(l4, dtype = 'object')
n4.shape

In [ ]:
print(l2[1][1], n2[1][1])

print(l2[1][1], n2[1,1])

print(l3[0][1][0], n3[0,1,0])

print(l2[1])

print(n2[1])


In [ ]:
narr = np.arange(1,50)
narr

In [ ]:
np.linspace(1,2,5) # 1 or 2 ko incclude krke 5 elements dega 1 or 2 k bich m

In [ ]:
np.linspace(1,10,5)

In [ ]:
np.ones(shape = (4,5))

In [18]:
np.ones(shape = (2,4,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [19]:
np.ones(shape = (3,2,4,5))

array([[[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]],


       [[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]],


       [[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]]])

In [20]:
np.zeros(shape = (4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [21]:
l1 = np.eye(3,4) #give identity matrix

In [22]:
l1

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [23]:
l1*3 

array([[3., 0., 0., 0.],
       [0., 3., 0., 0.],
       [0., 0., 3., 0.]])

In [24]:
np.diag([1,2,3,4,5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [25]:
narr = np.arange(1,101)


In [26]:
narr = narr.reshape((10,10))
narr.shape

(10, 10)

In [27]:
narr

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [28]:
np.random.rand(3,2,2)

array([[[0.55345377, 0.86502964],
        [0.9921775 , 0.34755196]],

       [[0.09036725, 0.01434534],
        [0.42955214, 0.3767178 ]],

       [[0.87018756, 0.3029657 ],
        [0.6717083 , 0.5035019 ]]])

In [29]:
np.random.randn(3,2,2) # n is used for normal distribution

array([[[-2.55341791,  1.57996185],
        [ 0.12121475,  1.19032508]],

       [[-0.53993621,  1.51524472],
        [-0.30913579,  1.41196791]],

       [[ 1.15508382,  1.29271703],
        [-0.38203331, -1.8051277 ]]])

In [30]:
np.random.randint(1,101,size = (5,2))

array([[64, 78],
       [49,  9],
       [18, 99],
       [36, 70],
       [35, 61]])

In [31]:
np.random.random(size = (5,2))

array([[0.22100942, 0.72019795],
       [0.24486715, 0.71362678],
       [0.99904332, 0.07278548],
       [0.11342245, 0.21075406],
       [0.69472265, 0.88731891]])

In [32]:
np.random.choice(np.array([1,2,3,4,5,6,7,8,9]),size =(5,), replace = True, p =[0,0,0,0.1,0.2,0.2,0.4,0.1,0])

array([7, 4, 7, 5, 6])

In [33]:
narr = np.arange(1,101).reshape((10,10)) # sirf rows ko shuffle krega rows k andr k elements ko shuffle nhi krega kuki ek dimenssion m hi shuffling krta h
narr

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [34]:
np.random.shuffle(narr) # sirf rows ko shuffle krega rows k andr k elements ko shuffle nhi krega kuki ek dimenssion m hi shuffling krta h
narr


array([[ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90]])

In [35]:
narr = np.arange(1,101) # iske andr elements shuffle honge kuki ek hi element hai
narr

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [36]:
np.random.shuffle(narr)
narr

array([ 33,   6,  50,  17,  78,  66,  48,  45,   5,  64,  54,  18,   3,
        62,  49,  15,  59,  73,  20,  91,  77,  65,  61,  16,  63,  93,
        94,   8,  70,  80,  96,  32,  53,  69,  26,  40,  92,  22,  10,
        21,  76,  42,  84,  51,   2,  47,  11,  85,  37,  72,  57,  19,
        39,  86,  71,  89,   7,  27,  38,  88,  25,  23,  82,  67,   4,
        60,  52,  87,  90,  56,  68,  97,  12,  14,  99,  28,  36,  31,
        30, 100,   1,  41,  55,  95,  74,  44,  29,  46,  75,  81,  34,
        98,  13,  35,   9,  79,  83,  24,  43,  58])

In [37]:
narr = narr.reshape(5,2,-1) # -1 ka mtlv h ki 
                    #jis dimenssion m bhi hum -1 likhenge vo baaki dimenssions ko analyse krega or check krega 
                    #ki iss vale dimenssion m kitne elements aayenge ya kitne array aayeenge 
                    #or phrr vo automaticcally elements set krdega
narr

array([[[ 33,   6,  50,  17,  78,  66,  48,  45,   5,  64],
        [ 54,  18,   3,  62,  49,  15,  59,  73,  20,  91]],

       [[ 77,  65,  61,  16,  63,  93,  94,   8,  70,  80],
        [ 96,  32,  53,  69,  26,  40,  92,  22,  10,  21]],

       [[ 76,  42,  84,  51,   2,  47,  11,  85,  37,  72],
        [ 57,  19,  39,  86,  71,  89,   7,  27,  38,  88]],

       [[ 25,  23,  82,  67,   4,  60,  52,  87,  90,  56],
        [ 68,  97,  12,  14,  99,  28,  36,  31,  30, 100]],

       [[  1,  41,  55,  95,  74,  44,  29,  46,  75,  81],
        [ 34,  98,  13,  35,   9,  79,  83,  24,  43,  58]]])

In [38]:
narr[1,1,5]

np.int64(40)

In [39]:
narr[1,1,5] = 350
narr

array([[[ 33,   6,  50,  17,  78,  66,  48,  45,   5,  64],
        [ 54,  18,   3,  62,  49,  15,  59,  73,  20,  91]],

       [[ 77,  65,  61,  16,  63,  93,  94,   8,  70,  80],
        [ 96,  32,  53,  69,  26, 350,  92,  22,  10,  21]],

       [[ 76,  42,  84,  51,   2,  47,  11,  85,  37,  72],
        [ 57,  19,  39,  86,  71,  89,   7,  27,  38,  88]],

       [[ 25,  23,  82,  67,   4,  60,  52,  87,  90,  56],
        [ 68,  97,  12,  14,  99,  28,  36,  31,  30, 100]],

       [[  1,  41,  55,  95,  74,  44,  29,  46,  75,  81],
        [ 34,  98,  13,  35,   9,  79,  83,  24,  43,  58]]])

In [40]:
narr.reshape(-1,)

array([ 33,   6,  50,  17,  78,  66,  48,  45,   5,  64,  54,  18,   3,
        62,  49,  15,  59,  73,  20,  91,  77,  65,  61,  16,  63,  93,
        94,   8,  70,  80,  96,  32,  53,  69,  26, 350,  92,  22,  10,
        21,  76,  42,  84,  51,   2,  47,  11,  85,  37,  72,  57,  19,
        39,  86,  71,  89,   7,  27,  38,  88,  25,  23,  82,  67,   4,
        60,  52,  87,  90,  56,  68,  97,  12,  14,  99,  28,  36,  31,
        30, 100,   1,  41,  55,  95,  74,  44,  29,  46,  75,  81,  34,
        98,  13,  35,   9,  79,  83,  24,  43,  58])

In [41]:
#numpy supports slicing in a 2d array
narr = narr.reshape(5,2,-1)
narr[1:4]

array([[[ 77,  65,  61,  16,  63,  93,  94,   8,  70,  80],
        [ 96,  32,  53,  69,  26, 350,  92,  22,  10,  21]],

       [[ 76,  42,  84,  51,   2,  47,  11,  85,  37,  72],
        [ 57,  19,  39,  86,  71,  89,   7,  27,  38,  88]],

       [[ 25,  23,  82,  67,   4,  60,  52,  87,  90,  56],
        [ 68,  97,  12,  14,  99,  28,  36,  31,  30, 100]]])

In [42]:
narr[1:4,:,2:7]

array([[[ 61,  16,  63,  93,  94],
        [ 53,  69,  26, 350,  92]],

       [[ 84,  51,   2,  47,  11],
        [ 39,  86,  71,  89,   7]],

       [[ 82,  67,   4,  60,  52],
        [ 12,  14,  99,  28,  36]]])

In [43]:
narr[1:4,0,2:7] # 0 lgayenge to bss phli row hi aayegi hrr 2d array m se

array([[61, 16, 63, 93, 94],
       [84, 51,  2, 47, 11],
       [82, 67,  4, 60, 52]])

In [44]:
narr = np.arange(1,101).reshape((10,10))
narr

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [45]:
narr[3:7,4:8]

array([[35, 36, 37, 38],
       [45, 46, 47, 48],
       [55, 56, 57, 58],
       [65, 66, 67, 68]])

In [46]:
narr[3:7,4:8] = np.eye(4)
narr

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,   1,   0,   0,   0,  39,  40],
       [ 41,  42,  43,  44,   0,   1,   0,   0,  49,  50],
       [ 51,  52,  53,  54,   0,   0,   1,   0,  59,  60],
       [ 61,  62,  63,  64,   0,   0,   0,   1,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [47]:
n1 = np.array([1,2,3,4,5])
n2 = np.array([10,20,30,40,50])

In [48]:
n1+10

array([11, 12, 13, 14, 15])

In [49]:
n1+n2

array([11, 22, 33, 44, 55])

In [50]:

n1 = np.arange(1,21)
n1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [51]:
# fancy indexing - give the index which u want to print

n1[[1,4,10]]

array([ 2,  5, 11])

In [52]:
np.random.shuffle(n1)
n1

array([ 1,  9, 20, 18,  3, 16,  7, 12, 13, 15,  5, 14,  6, 19,  8,  4,  2,
       17, 11, 10])

In [53]:
n1[[1,4,10]]

array([9, 3, 5])

In [54]:
# filtering
n1 > 10

array([False, False,  True,  True, False,  True, False,  True,  True,
        True, False,  True, False,  True, False, False, False,  True,
        True, False])

In [55]:
n1[n1 > 10]

array([20, 18, 16, 12, 13, 15, 14, 19, 17, 11])

In [56]:
narr = np.arange(1,101)
narr

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [57]:
narr = narr.reshape(10,10)
narr

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [58]:
n1[[1,4,7]]

array([ 9,  3, 12])

In [59]:
narr[[1,4,7],[0,3,6]]

array([11, 44, 77])

In [60]:
# also there is a way in fancy indexing- 
# we can put false on those row no.s which we dont want to call and put true on those row no.s which we want to call
narr[[True,True,False,False,True,True,True,False,False,True]]


array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [61]:
narr > 50


array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [62]:
narr[narr > 50]

array([ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,
        64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,
        77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,
        90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [63]:
n1

array([ 1,  9, 20, 18,  3, 16,  7, 12, 13, 15,  5, 14,  6, 19,  8,  4,  2,
       17, 11, 10])

In [64]:
n2 = np.array([[[1,2],[3,4],[5,6]],[[10,20],[30,40],[50,60]]])

In [65]:
n2

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[10, 20],
        [30, 40],
        [50, 60]]])

In [66]:
np.sum(n2)

np.int64(231)

In [67]:
#axis - axis can be defined as the index of the dimenssions of the shape

n2.shape


(2, 3, 2)

In [68]:
#axis - axis can be defined as the index of the dimenssions of the shape
# her we give value 0 it means it corresponds to 3d array and give sum of both 2d array present in 3d rray

n2.sum(axis = 0)

array([[11, 22],
       [33, 44],
       [55, 66]])

In [69]:
n2.sum(axis = 1)

array([[  9,  12],
       [ 90, 120]])

In [70]:
n2.sum(axis = 2)

array([[  3,   7,  11],
       [ 30,  70, 110]])

In [71]:
n2.max(axis = 1)

array([[ 5,  6],
       [50, 60]])

In [72]:
n2.max(axis = 0)

array([[10, 20],
       [30, 40],
       [50, 60]])

In [73]:
n3 = np.array([[1,2],[3,4],[5,6]])
n3

array([[1, 2],
       [3, 4],
       [5, 6]])

In [74]:
for i in np.nditer(n3):
    print(i)

1
2
3
4
5
6


In [75]:
for i in np.ndenumerate(n3):
    print(i)

((0, 0), np.int64(1))
((0, 1), np.int64(2))
((1, 0), np.int64(3))
((1, 1), np.int64(4))
((2, 0), np.int64(5))
((2, 1), np.int64(6))


In [76]:
n1 = np.array([1,2,3])
n2 = np.array([10,20,30])

In [77]:
np.vstack((n1,n2))


array([[ 1,  2,  3],
       [10, 20, 30]])

In [78]:
np.hstack((n1,n2))

array([ 1,  2,  3, 10, 20, 30])

In [79]:
np.concatenate((n1,n2))

array([ 1,  2,  3, 10, 20, 30])

In [80]:
np.stack((n1,n2),axis = 0) # puri ki ki puri row add hoyengi ek dusre se

array([[ 1,  2,  3],
       [10, 20, 30]])

In [81]:
np.stack((n1,n2),axis = 1) # puri row ka hrr ek element combine krke alag alag nyi row bnayega apne according


array([[ 1, 10],
       [ 2, 20],
       [ 3, 30]])

In [82]:
#split it is used just opposite to stack 
# u just have to give the array name and then indexing .... in how many parts u want to divide the array
np.hsplit(narr,2)


[array([[ 1,  2,  3,  4,  5],
        [11, 12, 13, 14, 15],
        [21, 22, 23, 24, 25],
        [31, 32, 33, 34, 35],
        [41, 42, 43, 44, 45],
        [51, 52, 53, 54, 55],
        [61, 62, 63, 64, 65],
        [71, 72, 73, 74, 75],
        [81, 82, 83, 84, 85],
        [91, 92, 93, 94, 95]]),
 array([[  6,   7,   8,   9,  10],
        [ 16,  17,  18,  19,  20],
        [ 26,  27,  28,  29,  30],
        [ 36,  37,  38,  39,  40],
        [ 46,  47,  48,  49,  50],
        [ 56,  57,  58,  59,  60],
        [ 66,  67,  68,  69,  70],
        [ 76,  77,  78,  79,  80],
        [ 86,  87,  88,  89,  90],
        [ 96,  97,  98,  99, 100]])]

In [83]:
#broadcasting - if there is 1d array and any other array then we can perform calculations on them with help of broadcasting
#.               but uski condition ye h ki dusri array or 1d array k no. of columns same hone chahiye 
n1 = np.arange(1,13).reshape(4,3)
n1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [84]:
n1 = n1 + np.array([10,20,30]) # yha ek 1d row array m puri n1 matrix add hogyi
n1

array([[11, 22, 33],
       [14, 25, 36],
       [17, 28, 39],
       [20, 31, 42]])

In [85]:
n1 = n1 + np.array([[10],[20],[30],[40]]) # yha ek 1d col. array n1 m add hogyi
n1

array([[21, 32, 43],
       [34, 45, 56],
       [47, 58, 69],
       [60, 71, 82]])

In [86]:
# agr ek col matrix hogi or ek row matrix hogi to vo dono hi apne apne dimenssions k according broadcasting krengi
np.array([1,2,3,4]) + np.array([[10],[20],[30]])
# just like iss example m hmare pss ek 3*4 matrix bngyi by broadcasting

array([[11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 33, 34]])

In [87]:
# input data from a text file
ne = np.loadtxt('population.txt')

In [88]:
np.max(ne, axis = 0)[1:], ne[np.argmax(ne, axis = 0)][1:,0]

(array([77400., 59400., 48300.]), array([1903., 1904., 1900.]))

In [89]:
# matrix multiplication - .dot and @ are used for matrix multiplication
m1 = np.arange(1,13).reshape(3,4)
m2 = np.arange(1,7).reshape(2,3)
m2.dot(m1)

array([[ 38,  44,  50,  56],
       [ 83,  98, 113, 128]])

In [90]:
m2@m1

array([[ 38,  44,  50,  56],
       [ 83,  98, 113, 128]])