In [1]:
import pandas as pd

ModuleNotFoundError: No module named 'pandas'

# Pandas - used for data manipulation
- two types of data structures: - series : 1d array
                                - dataframe : 2d array
- 

In [2]:
pip install pandas


[notice] A new release of pip is available: 25.0.1 -> 25.1.1
[notice] To update, run: /opt/homebrew/Cellar/jupyterlab/4.4.0_1/libexec/bin/python -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [3]:
import pandas as pd

In [4]:
import numpy as np

In [5]:
pip install --upgrade pip

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 7.6 MB/s eta 0:00:00a 0:00:01
  Attempting uninstall: pip
    Found existing installation: pip 25.0.1
    Uninstalling pip-25.0.1:
      Successfully uninstalled pip-25.0.1
Note: you may need to restart the kernel to use updated packages.


In [6]:
print(pd.__version__)

2.2.3


In [7]:
l1 = np.array([10,20,30,40,50])

In [8]:
pds = pd.Series(l1)

In [9]:
pds

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [10]:
pds = pd.Series(l1,index = ['a','b','c','d','e'],dtype ='f8')

In [11]:
pds

a    10.0
b    20.0
c    30.0
d    40.0
e    50.0
dtype: float64

In [12]:
d1 = {'A' : 10, 'B' : 20, 'C' : 30}

In [13]:
d1

{'A': 10, 'B': 20, 'C': 30}

In [14]:
pds = pd.Series(d1)
pds

A    10
B    20
C    30
dtype: int64

# dataframe - 2d matrix
- individual col. = pandas ki series
- harr column ko ek naam de skte h or uss name se alag alag column ko as a series access kr skte h

In [15]:
pds['A']

np.int64(10)

In [16]:
marks = {
    'phy' : [45,65,76,45,23],
    'math' : [23,65,76,87,43],
    'sci' : [45,68,48,84,95]}

In [17]:
marks

{'phy': [45, 65, 76, 45, 23],
 'math': [23, 65, 76, 87, 43],
 'sci': [45, 68, 48, 84, 95]}

In [18]:
df1 = pd.DataFrame(marks,index = ['a','b','c','d','e'])

In [19]:
df1

phy  math  sci
a   45    23   45
b   65    65   68
c   76    76   48
d   45    87   84
e   23    43   95

In [20]:
df = pd.DataFrame(marks,index = ['a','b','c','d','e'],columns = ['phy','math'])

In [21]:
df

phy  math
a   45    23
b   65    65
c   76    76
d   45    87
e   23    43

In [22]:
na = np.random.randint(1,101,size = (10,3))

In [23]:
df2 =pd.DataFrame(na,columns=['phys','chemi','maths'])

In [24]:
df2

phys  chemi  maths
0    68     75     67
1    32     26     68
2    35     92     75
3    38     92      6
4    17     31     68
5    61      7     84
6    17     99     14
7    47     39     88
8    39     76     84
9    92      9     46

In [25]:
df2['sst'] = np.random.randint(1,101,size = (10,))
df2

phys  chemi  maths  sst
0    68     75     67   79
1    32     26     68   99
2    35     92     75   43
3    38     92      6   25
4    17     31     68   46
5    61      7     84   55
6    17     99     14    7
7    47     39     88   47
8    39     76     84    5
9    92      9     46   54

In [26]:
df2.head(3) # starting 3 rows lakr deta h

phys  chemi  maths  sst
0    68     75     67   79
1    32     26     68   99
2    35     92     75   43

In [27]:
df2.tail(3) # last vali 3 rows ko lakr deta h

phys  chemi  maths  sst
7    47     39     88   47
8    39     76     84    5
9    92      9     46   54

In [28]:
df2.values # numpy array print krdeta h

array([[68, 75, 67, 79],
       [32, 26, 68, 99],
       [35, 92, 75, 43],
       [38, 92,  6, 25],
       [17, 31, 68, 46],
       [61,  7, 84, 55],
       [17, 99, 14,  7],
       [47, 39, 88, 47],
       [39, 76, 84,  5],
       [92,  9, 46, 54]])

In [29]:
df2.columns

Index(['phys', 'chemi', 'maths', 'sst'], dtype='object')

In [30]:
# convert to csv: comma separated file

df2.to_csv('marks.csv')

In [31]:
df2.to_csv('marks.csv', sep =',')

In [32]:
df2.to_csv('marks.csv',index = False) #index htt jayega

In [35]:
# Unnamed : jis index col. ka naam ni h vo usko vo vali value dedega
df2.to_csv('marks.csv',index = False, index_label = 'Unnamed : 0')

In [36]:
df2

phys  chemi  maths  sst
0    68     75     67   79
1    32     26     68   99
2    35     92     75   43
3    38     92      6   25
4    17     31     68   46
5    61      7     84   55
6    17     99     14    7
7    47     39     88   47
8    39     76     84    5
9    92      9     46   54

In [37]:
 df2.drop(columns = ['sst']) # jis bhi column ka naam denge vo vsla col. del. hojega

phys  chemi  maths
0    68     75     67
1    32     26     68
2    35     92     75
3    38     92      6
4    17     31     68
5    61      7     84
6    17     99     14
7    47     39     88
8    39     76     84
9    92      9     46

In [38]:
# drop changes krke ek nya dataset lekr aara h but 
# we can use inplace so that ussi dataset m change hojaye
df2.drop(columns = ['sst'],inplace = True)

In [39]:
df2

phys  chemi  maths
0    68     75     67
1    32     26     68
2    35     92     75
3    38     92      6
4    17     31     68
5    61      7     84
6    17     99     14
7    47     39     88
8    39     76     84
9    92      9     46

# Pandas Functions : 
- 


In [85]:
df2.describe()

phys      chemi      maths
count  10.000000  10.000000  10.000000
mean   41.400000  43.000000  41.100000
std    34.766523  28.339215  23.076925
min     2.000000   2.000000  11.000000
25%    10.000000  23.250000  21.250000
50%    39.500000  41.000000  39.000000
75%    64.750000  54.000000  60.500000
max    94.000000  94.000000  75.000000

In [86]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   phys    10 non-null     int64
 1   chemi   10 non-null     int64
 2   maths   10 non-null     int64
dtypes: int64(3)
memory usage: 372.0 bytes


In [87]:
df['phy'] # jis column k naam denge vhi col. aajega

a    45
b    65
c    76
d    45
e    23
Name: phy, dtype: int64

In [88]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, a to e
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   phy     5 non-null      int64
 1   math    5 non-null      int64
dtypes: int64(2)
memory usage: 292.0+ bytes


In [89]:
df.loc['a','math']

np.int64(23)

In [90]:
df.loc['a']

phy     45
math    23
Name: a, dtype: int64

In [91]:
df.loc[['a','c','d'],'phy']

a    45
c    76
d    45
Name: phy, dtype: int64

In [92]:
df.iloc[0,1]

np.int64(23)

In [93]:
df1

phy  math  sci
a   45    23   45
b   65    65   68
c   76    76   48
d   45    87   84
e   23    43   95

In [94]:
df2

phys  chemi  maths
0    25     17     20
1    19     78     53
2    55     94     20
3    68     27     75
4    94     54     66
5     3     48     25
6     7      2     52
7    87     34     63
8    54     22     26
9     2     54     11

In [100]:
df2.iloc[2:6, 1:3]

chemi  maths
2     94     20
3     27     75
4     54     66
5     48     25

In [102]:
df2['phys'] > 80

0    False
1    False
2    False
3    False
4     True
5    False
6    False
7     True
8    False
9    False
Name: phys, dtype: bool

In [103]:
df2[df2['phys'] > 80]

phys  chemi  maths
4    94     54     66
7    87     34     63

In [41]:
temp = pd.read_csv('weather_data_cities.csv')

In [42]:
temp

day      city  temperature  windspeed   event
0   1/1/2017  new york           32          6    Rain
1   1/2/2017  new york           36          7   Sunny
2   1/3/2017  new york           28         12    Snow
3   1/4/2017  new york           33          7   Sunny
4   1/1/2017    mumbai           90          5   Sunny
5   1/2/2017    mumbai           85         12     Fog
6   1/3/2017    mumbai           87         15     Fog
7   1/4/2017    mumbai           92          5    Rain
8   1/1/2017     paris           45         20   Sunny
9   1/2/2017     paris           50         13  Cloudy
10  1/3/2017     paris           54          8  Cloudy
11  1/4/2017     paris           42         10  Cloudy

In [43]:
temp['temperature'] >= 90

0     False
1     False
2     False
3     False
4      True
5     False
6     False
7      True
8     False
9     False
10    False
11    False
Name: temperature, dtype: bool

In [44]:
d = temp[temp['temperature'] >= 90]
d

day    city  temperature  windspeed  event
4  1/1/2017  mumbai           90          5  Sunny
7  1/4/2017  mumbai           92          5   Rain

In [116]:
d[d['city'] == 'mumbai']['day']

4    1/1/2017
7    1/4/2017
Name: day, dtype: object

In [119]:
temp.columns #sare columns utha kr dedega

Index(['day', 'city', 'temperature', 'windspeed', 'event'], dtype='object')

In [118]:
temp.columns.get_loc('city')

1

In [120]:
df['phy'].unique

<bound method Series.unique of a    45
b    65
c    76
d    45
e    23
Name: phy, dtype: int64>

In [121]:
a = np.array([1,1,1,1,2,3,4,2,3,4,2,3,4])

In [122]:
np.unique(a)

array([1, 2, 3, 4])

In [123]:
np.unique(a,return_counts=True)

(array([1, 2, 3, 4]), array([4, 3, 3, 3]))

In [125]:
df2['chemi'].apply(lambda x: x**2)

0     289
1    6084
2    8836
3     729
4    2916
5    2304
6       4
7    1156
8     484
9    2916
Name: chemi, dtype: int64

In [131]:
 df2.sort_values(by = 'phys',axis = 0, ascending = False)

phys  chemi  maths
4    94     54     66
7    87     34     63
3    68     27     75
2    55     94     20
8    54     22     26
0    25     17     20
1    19     78     53
6     7      2     52
5     3     48     25
9     2     54     11

In [136]:
pds

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [45]:
#one hot encoding
pdd = pd.get_dummies(pds)

In [135]:
pdd

10     20     30     40     50
0   True  False  False  False  False
1  False   True  False  False  False
2  False  False   True  False  False
3  False  False  False   True  False
4  False  False  False  False   True

In [137]:
gdf = temp.groupby(by = 'city')


In [138]:
for city, group in gdf:
    print(city)
    print(group)
    print()

mumbai
        day    city  temperature  windspeed  event
4  1/1/2017  mumbai           90          5  Sunny
5  1/2/2017  mumbai           85         12    Fog
6  1/3/2017  mumbai           87         15    Fog
7  1/4/2017  mumbai           92          5   Rain

new york
        day      city  temperature  windspeed  event
0  1/1/2017  new york           32          6   Rain
1  1/2/2017  new york           36          7  Sunny
2  1/3/2017  new york           28         12   Snow
3  1/4/2017  new york           33          7  Sunny

paris
         day   city  temperature  windspeed   event
8   1/1/2017  paris           45         20   Sunny
9   1/2/2017  paris           50         13  Cloudy
10  1/3/2017  paris           54          8  Cloudy
11  1/4/2017  paris           42         10  Cloudy



In [139]:
gdf['temperature'].max()

city
mumbai      92
new york    36
paris       54
Name: temperature, dtype: int64

In [148]:
gdf = temp.groupby(by = 'day')['temperature'].mean()
# for day, group in gdf:
#     print(day)
#     print(group)
    # print()
gdf

day
1/1/2017    55.666667
1/2/2017    57.000000
1/3/2017    56.333333
1/4/2017    55.666667
Name: temperature, dtype: float64

In [142]:
temp.pivot(columns='city',index = 'day')

temperature                windspeed                 event           \
city          mumbai new york paris    mumbai new york paris mumbai new york   
day                                                                            
1/1/2017          90       32    45         5        6    20  Sunny     Rain   
1/2/2017          85       36    50        12        7    13    Fog    Sunny   
1/3/2017          87       28    54        15       12     8    Fog     Snow   
1/4/2017          92       33    42         5        7    10   Rain    Sunny   

                  
city       paris  
day               
1/1/2017   Sunny  
1/2/2017  Cloudy  
1/3/2017  Cloudy  
1/4/2017  Cloudy

In [149]:
d1 = {
    'A' : [10,20,30,40],
    'B' : [3,4,5,6]}
d2 = {
    'A' : [ 30,40,50,60],
    'C' : [3,4,5,6]}

In [151]:
df4 = pd.DataFrame(d1)
df5 = pd.DataFrame(d2)

In [153]:
df6 = pd.concat([df4,df5]) # somthing similar to join in SQL
df6

A    B    C
0  10  3.0  NaN
1  20  4.0  NaN
2  30  5.0  NaN
3  40  6.0  NaN
0  30  NaN  3.0
1  40  NaN  4.0
2  50  NaN  5.0
3  60  NaN  6.0

In [158]:
df6 = pd.concat([df4,df5],ignore_index = True) # new indices 
df6

A    B    C
0  10  3.0  NaN
1  20  4.0  NaN
2  30  5.0  NaN
3  40  6.0  NaN
4  30  NaN  3.0
5  40  NaN  4.0
6  50  NaN  5.0
7  60  NaN  6.0

In [157]:
df6 = pd.concat([df4,df5],ignore_index = True,join = 'inner') # somthing similar to join in SQL : intersection(inner)
df6

A
0  10
1  20
2  30
3  40
4  30
5  40
6  50
7  60

In [160]:
df6 = pd.concat([df4,df5],axis = 1) # horizontal stack.  ....vertical stack for axis = 0
df6

A  B   A  C
0  10  3  30  3
1  20  4  40  4
2  30  5  50  5
3  40  6  60  6

In [162]:
# in real merge work as a join of SQL
mdf3 = pd.merge(df4,df5) # inner join
mdf3

A  B  C
0  30  5  3
1  40  6  4

In [163]:
mdf3 = pd.merge(df4,df5,how = 'right') #  right outer join
mdf3

A    B  C
0  30  5.0  3
1  40  6.0  4
2  50  NaN  5
3  60  NaN  6

In [164]:
mdf3 = pd.merge(df4,df5,how = 'left') #  left outer join
mdf3

A  B    C
0  10  3  NaN
1  20  4  NaN
2  30  5  3.0
3  40  6  4.0

In [165]:
# dropna() is used to remove all the rows having none values
mdf3.dropna()

A  B    C
2  30  5  3.0
3  40  6  4.0

In [168]:
# we cant remove all all rows if there are many rows containing none values 
# so we can use fillna : it fill the none values with the average of the data
mdf3.fillna(mdf3.mean())

A  B    C
0  10  3  3.5
1  20  4  3.5
2  30  5  3.0
3  40  6  4.0

In [170]:
# iske andr hum none value k nearest upr ya niche vali
mdf3.interpolate('linear',limit_direction='both')

A  B    C
0  10  3  3.0
1  20  4  3.0
2  30  5  3.0
3  40  6  4.0